version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: ptwin-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "60", "1000", "--loglevel", "warning"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
  app:
    build:
      context: ./backend
    container_name: ptwin-app
    ports:
      - "8081:8081"
    env_file:
      - backend/.env
    depends_on:
      - redis
    volumes:
      - ./backend/src:/app/src
    command: ["uvicorn", "src.predictive_api:app", "--reload", "--host", "0.0.0.0", "--port", "8081"]
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:8081/health"]
      interval: 20s
      timeout: 5s
      retries: 5
